root = "."
tmp_dir = "tmp"

[build]
    cmd = "templ generate && go build -o /tmp/main ."
    bin = "./tmp/main"
    include_ext = ["go", "templ"]

    //exclude_dir = ["assets"]
[log]
    time = true

[serve]
    command = "&& ./tmp/main"