// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func homepage() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<head><script src=\"https://unpkg.com/htmx.org\"></script><script src=\"https://cdn.tailwindcss.com\"></script></head><script>\n        document.addEventListener('DOMContentLoaded', () => {\n            const inputField = document.getElementById('cryptocurrency');\n            const submitButton = document.getElementById('submit-button');\n\n            inputField.addEventListener('input', () => {\n                const inputValue = inputField.value;\n                const encodedValue = encodeURIComponent(inputValue);\n                const newAction = `/price?ticker=${encodedValue}`;\n                submitButton.setAttribute('hx-get', newAction);\n                console.log('hx-get updated to:', submitButton.getAttribute('hx-get')); \n                htmx.process(submitButton)// Debugging line\n            });\n        });\n    </script><div class=\"text-center py-8\"><h1 class=\"text-3xl font-bold  mb-4\">Welcome to crypto price checker</h1><input type=\"text\" id=\"cryptocurrency\" name=\"cryptocurrency\" class=\"border-2 border-gray-300 bg-white h-10 px-5 pr-16 rounded-lg text-sm focus:outline-none\" placeholder=\"Enter  cryptocurrency name (not ticker)...\"> <button hx-get=\"/price\" id=\"submit-button\" hx-target=\"#crypto-price\" class=\"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded\">Submit</button><div id=\"crypto-price\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
